<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_TwoFactorAuthentication
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<form method="post" action="" id="send-form" data-mage-init='{"form": {}, "validation": {}}'>
    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?= /* @noEscape */ __('Verification') ?></span></legend><br />
        <input name="form_key" type="hidden" value="<?= /* @noEscape */ $block->getFormKey() ?>" />
        <p class="admin__field-info"><?= /* @noEscape */ __('Enter the code to complete sign in.') ?></p>
        <div class="admin__field _required">
            <label for="password" class="admin__field-label"><span><?= /* @noEscape */ __('Code:') ?></span></label>
            <div class="admin__field-control">
                <input type="password" id="password" name="password" value="" data-validate="{required:true}"
                    class="admin__control-text" />
            </div>
        </div>
        <div class="form-actions">
            <div class="actions">
                <button class="action-retrieve action-primary"
                    type="submit"><span><?= /* @noEscape */ __('Login') ?></span></button>
            </div>
        </div>
    </fieldset>
</form>